--q9
Select CITY
From LOCATIONS
where COUNTRY_ID = 'IT';
--q10 

select CITY
from locations
where COUNTRY_ID != 'IN' OR COUNTRY_ID != 'CH';

--q11

select JOB_TITLE

from JOBS

where MIN_SALARY > 8000 and MAX_SALARY < 15000;

--Q12

SELECT Phone_number
FROM EMPLOYEES
WHERE DEPARTMENT_ID = '90' AND JOB_ID != 'IT_PROG';

--q13

Select  HIRE_DATE,EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL
from EMPLOYEES
WHERE HIRE_DATE > '12-DEC-07';

--Q14

Select  HIRE_DATE,EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL
from EMPLOYEES 
WHERE HIRE_DATE > '12-DEC-07' AND DEPARTMENT_ID = '100';

--q15
Select  HIRE_DATE,DEPARTMENT_ID,EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL
from EMPLOYEES 
WHERE HIRE_DATE > '12-DEC-07' AND DEPARTMENT_ID != '100';


